### ISSUE TITLE
Ability to dump object data to console

### ISSUE THREAD

**Issue by kid2407** [League-of-Foundry-Developers/foundryvtt-devMode#12]
**Is your feature request related to a problem? Please describe.**
It is always so much fiddling to get data of certain objects, especially their id, via console and digging around in the HTML.

**Describe the solution you'd like**
I wish there was a "dump data" button / context menu / whatever to allow me to just quickly get data on any object / item that is around.

**Describe alternatives you've considered**
Keeping it as it is, I guess. Just would things a bit easier, with less steps to just get the relevant data.

**Additional context**
---

**Comment by akrigline** [comment]
Done in 1.5.0
