### ISSUE TITLE
Add the posibility to configure the available loglevels

### ISSUE THREAD

**Issue by ghost91-** [League-of-Foundry-Developers/foundryvtt-devMode#17]
**Is your feature request related to a problem? Please describe.**
Currently, the order of log levels makes it difficult to easily compare the configured log level against the log level of a given log statement. Additionally, there are more log levels than I actually need.

**Describe the solution you'd like**
In order to solve the order problem in a backwards compatible way, I would be grate to be able to provide a list of number-lable pairs which would be used as possible values for log levels. This could (optionally) be passed in as part of the `options` in the call to `registerPackageDebugFlag`

**Describe alternatives you've considered**
* The order could simply be changed but that's a breaking change
* I could manually check against all different levels but that's quite tedious

**Additional context**
See the discussion following https://discord.com/channels/732325252788387980/732325252788387983/882371382443384953

**Comment by akrigline** [comment]
Done in v1.4.0
