### ISSUE TITLE
Always Unpause

### ISSUE THREAD

**Issue by akrigline** [League-of-Foundry-Developers/foundryvtt-devMode#2]
An option to always unpause the game when loading it up would be nice.

**Comment by kakaroto** [comment]
```js
Hooks.on("ready", () => {
  if (game.paused) game.togglePause();
});
```

Pause state is local. A user can unpause themselves with that. Server does nothing to prevent any operation on pause, and the state is not stored anywhere other than in RAM (with it being on by default on world launch). So far that I can tell, server side flag is only used to send it to the client when they receive the world data. Only restriction is that only a GM can push a 'toggle pause' command to the other players, and affect the server-side flag.

**Comment by zeel01** [comment]
@kakaroto Ah, brilliant.

**Comment by akrigline** [comment]
Excellent. I'll put in a new option defaulting true which executes this.
