### ISSUE TITLE
Tag gives sidebar a horizontal scroll

### ISSUE THREAD

**Issue by arcanistzed** [League-of-Foundry-Developers/foundryvtt-devMode#20]
**Environment Details**
- Foundry Core Version: v9p2
- System & Version: dnd5e 1.4.3
- OS & Browser: Linux Mint Chrome
- Hosting: Self Hosted

**Describe the bug**
Dev Mode tag has a `right: -1px` CSS property which gives the sidebar a horizontal scroll bar:
![CopyQ JyTBdC](https://user-images.githubusercontent.com/82790112/134407362-c6ad7476-93d4-4475-a74d-5ec38e3949be.png)

**To Reproduce**
1. Go to Sidebar
2. See horizontal scrollbar

**Expected behavior**
I expect no horizontal scollbar

**Solution**
Set the `right` CSS property to `0`: `right: 0;`

**Comment by akrigline** [comment]
Dang, must be something new from v9 css.
