### ISSUE TITLE
The sidebar may render incorrectly if you switch tabs too soon.

### ISSUE THREAD

**Issue by zeel01** [League-of-Foundry-Developers/foundryvtt-devMode#29]
**Environment Details**
- Foundry Core Version: 9 (or 8)
- System & Version: n/a
- OS & Browser: Chrome
- Hosting: n/a

**Describe the bug**
If you switch sidebar quickly while Foundry loads, the chat tab might render inside of the current tab.

**To Reproduce**
1. Enable dev mode
2. Reload Foundry
3. *Quickly* click on a sidebar tab other than chat
4. After a moment, half of the tab will be replaced with chat.

This doesn't appear to be related directly to the sidebar document ids, as disabling those features has no effect on the issue.

**Expected behavior**
That this wouldn't happen

**Screenshots**
![dev-mode-sidebar](https://user-images.githubusercontent.com/1721836/147134718-a5092ee5-6a0d-4d41-8386-2b15e0cfb6ff.gif)

**Comment by akrigline** [comment]
I bet changing this to async will fix:

`Hooks.on('renderChatMessage', (chatMessage, html) => {`

the `renderSidebarDirectory` one too

We're probably blocking a thread somewhere and violating an assumption when there's a lot of chat being iterated over, even without the feature it still runs a hook for each message.

**Comment by akrigline** [comment]
I'm able to reproduce this without devmode active, though devmode does make it easier to do because of the above. I'll make those changes anyway as they are smart ones.

**Comment by akrigline** [comment]
Alleviated with 1.9.0
