### ISSUE TITLE
Option to disable template caching.

### ISSUE THREAD

**Issue by zeel01** [League-of-Foundry-Developers/foundryvtt-devMode#4]
When modifying Handlebars templates it's frustrating to reload the page after making changes. However, it's simple enough to make Foundry reload templates when an application renders, by simply removing the template from the template cache. 

In Monster Blocks, I do the following:
```js
Hooks.on("renderActorSheet", (...args) => {	// This is just for debugging, it prevents this sheet's template from being cached.
	if (!debugging()) return; 

	let template = "modules/monsterblock/actor-sheet.html";
    delete _templateCache[template];
    console.debug(`Monster Block | removed "${template}" from _templateCache.`);
	console.log(args);
});
```
This specifically removes my template from the cache, but it's just as easy to purge the entire cache. It would be great if there were a feature of devMode that would purge the cache all the time, or otherwise disable the cache behavior.

**Comment by akrigline** [comment]
and then loadTemplate in the Application call stack re-populates the cache just fine? That _is_ nice.

**Comment by zeel01** [comment]
Let's see, aside from deleting the cache every time something renders, one *could* patch this function:
```js
/**
 * Get a template from the server by fetch request and caching the retrieved result
 * @param {string} path           The web-accessible HTML template URL
 * @returns {Promise<Function>}	  A Promise which resolves to the compiled Handlebars template
 */
async function getTemplate(path) {
	if ( !_templateCache.hasOwnProperty(path) ) {
    await new Promise((resolve, reject) => {
    	game.socket.emit('template', path, resp => {
    	  if ( resp.error ) return reject(new Error(resp.error));
	      const compiled = Handlebars.compile(resp.html);
	      Handlebars.registerPartial(path, compiled);
	      _templateCache[path] = compiled;
	      console.log(`Foundry VTT | Retrieved and compiled template ${path}`);
	      resolve(compiled);
	    });
    });
	} 
	return _templateCache[path];
}
```

**Comment by zeel01** [comment]
The best choice IMO is to patch `getTemplate` to first delete the cache entry, then call the original getTemplate function.
```js
const originalGetTemplate = getTemplate;
getTemplate = async function(path) {
    if (_templateCache.hasOwnProperty(path)) delete _templateCache[path];
    return originalGetTemplate(path);
}
```

**Comment by akrigline** [comment]
That seems like a solid way to do this, and I just put libwrapper's shim in last version so it'll be a simple and safe-ish patch.

**Comment by akrigline** [comment]
Done with 1.6.0
