### ISSUE TITLE
Error on JournalEntryPage editor rendering in 10.275

### ISSUE THREAD

**Issue by drewg13** [League-of-Foundry-Developers/foundryvtt-devMode#52]
**Environment Details**
- Foundry Core Version: 10.275
- System & Version:  multiple
- OS & Browser: Node/Win10/Firefox
- Hosting:  Self-hosted

**Describe the bug**
Error thrown when module enabled and edit button on JournalEntryPage clicked, see screenshot
Error does not occur when module is not enabled, error occurs under multiple systems including dnd5e 2.0.0-alpha2

**To Reproduce**
1. Open JournalEntry
2. Select Page
3. Click to edit
4. See error in console, no editor window renders

**Expected behavior**
Editor window opens

**Screenshots**
![image](https://user-images.githubusercontent.com/1455026/180614163-d2906c7f-6324-4fc8-9055-2c8b27800320.png)

**Comment by akrigline** [comment]
That's concerning. I have no idea why this could be happening. If anyone figures this out, please open a PR with a fix.

**Comment by drewg13** [comment]
I've narrowed it down to the Disable Template Cache option, which makes sense, given the error.  If I disable that, I no longer get the error.  I'm assuming something in that template cache is necessary to connect the partial to the path and is not being preserved.

**Comment by ben** [comment]
Yeah it looks like Foundry's template resolution has changed subtly. Maybe the solution is to not bypass the cache for paths that start with `templates/`?

Here's the foundry.js change:

![CleanShot 2022-09-08 at 08 46 55](https://user-images.githubusercontent.com/39902/189168369-1a51ef71-71f8-4c01-81d7-ebab01d4cfd4.jpg)

**Comment by ben** [comment]
Whoops, nope, that's not it. The patch just isn't passing along the `id` parameter. That's an easy fix. Lemme whip up a PR.
