### ISSUE TITLE
Suggestion:  Toggle to ban/unban all other players

### ISSUE THREAD

**Issue by BadIdeasBureau** [League-of-Foundry-Developers/foundryvtt-devMode#7]
**Is your feature request related to a problem? Please describe.**
The Foundry license allows mutliple instances to be run only in the case where only one of those instances is accessible to people other than the license holder.  One way to enforce this, and prevent player access while you've got multiple instnaces spun up is to ban all accounts in a world other than the license holder during prep (e.g. in the case where the license is used by A, the license holder, and B, their friend who also GMs, A and B can only prep games at the same time if all other accounts on A's world are inaccessible the players - as otherwise both A's world and B's world are open to "users other than the license holder").

**Describe the solution you'd like**
A quick toggle button to ban/unban all accounts other than those which are currently logged in. And ideally an obvious UI feature when this is active, as a reminder to unban and let the players back in.

**Describe alternatives you've considered**
Could be done via a macro.  Can also be done with a lot of clicking through the menu.  Either runs the risk of not noticing that you've left it in "Developer only" mode.

**Additional context**
N/A

**Comment by akrigline** [comment]
I'm not much sure this is in Dev-Mode's wheelhouse. It's often enough that while developing a dev needs both a GM and a Player account active at the same time (or multiple players even). I think this is firmly on the license holder's end to police.
