### ISSUE TITLE
Console warning about globalThis

### ISSUE THREAD

**Issue by caewok** [League-of-Foundry-Developers/foundryvtt-devMode#9]
**Environment Details**
- Foundry Core Version: 0.8.8
- System & Version: Ubuntu 20.04 in a docker environment
- OS & Browser: Mac OS X 10.15.7, Firefox 90.0.2
- Hosting: Vultr VM
(Forge, Self Hosted, Electron App, etc might be relevant)

**Describe the bug**
Getting tons of this warning in the logs:
> _dev-mode | accessing the module api on globalThis is deprecated and will be removed in a future update

**To Reproduce**
1. Install devMode
2. Activate devMode.
3. There is no step 3. 

**Expected behavior**
Expected no warning. It would be nice if this warning could be fixed so it stops flooding my console warnings. Makes it hard to see actual problems with my terrible module code :-)

**Comment by akrigline** [comment]
Are you accessing the devmode api on the `globalThis`, or are you getting it from `game.modules.get('_dev-mode')?.api`?

This was changed to be more in line with best-practices.

**Comment by caewok** [comment]
Yes, changing to this line in my logging function got rid of most of the warnings:
```js
const isDebugging = game.modules.get('_dev-mode')?.api?.getPackageDebugValue(MODULE_ID);
```
I am still getting two warnings at first log in when my module is enabled, and the only other time I call devMode is here:
```js
Hooks.once('devModeReady', ({ registerPackageDebugFlag }) => {
  registerPackageDebugFlag(MODULE_ID);
});
```
Could that be causing these warnings as well? The code I am using, I think, follows the current example on the readme. Thanks!

**Comment by akrigline** [comment]
Whoops, I definitely left an old call in the devmode code itself. Sorry about that. Will be fixed in next release.
